$(document).ready(function(){$("#seach_lesson_grade_level").change(function(){$("#seach_lesson_grade_level").css({"border-color":"#CCC"});$("#lesson_cmd").val("level");filterAction(1);})
$('#seach_lesson_subject_id').change(function(){$("#seach_lesson_subject_id").css({"border-color":"#CCC"});$("#lesson_cmd").val("subject");filterAction(2);})
$('#seach_lesson_topic_id').change(function(){if($("#seach_lesson_keyword").val()!=""){$("#lesson_cmd").val("topic");return false;}else{if($("#lesson_cmd").val()!='topic'){$("#lesson_cmd").val("topic");}
$('#seachLessonForm').submit();}})
$("#btn_go_to_list_lesson").click(function(){if($("#lesson_cmd").val()==''&&$("#seach_lesson_keyword").val()==''){$("#lesson_cmd").val("topic");}
var submit=true;if($("#seach_lesson_grade_level").val()===null){$("#seach_lesson_grade_level").css({"border-color":"#FF0000"});submit=false;return;}
if($("#seach_lesson_subject_id").val()===null){$("#seach_lesson_subject_id").css({"border-color":"#FF0000"});submit=false;}
if(submit)$('#seachLessonForm').submit();})
function filterAction(type){if($("#seach_lesson_keyword").val()!=""){grade_level=$('#seach_lesson_grade_level').val();subject_id=$('#seach_lesson_subject_id').val();callAjax(type,grade_level,subject_id);return false;}else{if(type==2){$('#seach_lesson_topic_id').val(-1);}
$('#seachLessonForm').submit();}}
function callAjax(type,grade_level,subject_id){var url="ajaxbf23.html?act=lesson&amp;code=get_search_select_list&amp;type="+type+'&subject_id='+subject_id+'&grade_level='+grade_level;$.ajax({url:url,type:"GET",dataType:"json",beforeSend:function(){},success:function(response){data=response.data;var subjects=toppics=[];if(type==1){$.each(data,function(key,val){if(key!=22&&key!=24&&key!=25){subjects.push("<option value='"+key+"'>"+val+"</option>");}});if(response.status==true){if(subjects.length>0){$('#seach_lesson_subject_id').prop("disabled",false);$('#seach_lesson_subject_id').html('<option value="" disabled selected style="display:none;">Chọn môn</option>'+subjects.join(""));}else{$('#seach_lesson_subject_id').html('<option value="" disabled selected style="display:none;">Chọn môn</option>');}}}else if(type==2){$.each(data,function(key,val){toppics.push("<option value='"+key+"'>"+val+"</option>");});if(response.status==true){if(subjects.length>0){$('#seach_lesson_topic_id').prop("disabled",false);$('#seach_lesson_topic_id').html('<option value="" disabled selected style="display:none;">Chọn chương/c.đề</option>'+toppics.join(""));}else{$('#seach_lesson_topic_id').html('<option value="" disabled selected style="display:none;">Chọn chương/c.đề</option>');}}}},complete:function(){}});}})